### ISSUE TITLE
Suggestion: mount winbox configuration volume

### ISSUE THREAD

**Issue by festlv** [fialakarel/docker-winbox#8]
Thank you for the docker image, it is very useful for linux users.
One suggestion is to add the following argument to command in README.md:
```--volume "$HOME/.local/share/winbox:/root/.wine/drive_c/users/root/Application Data/Mikrotik/Winbox" \```
With this, the session data and all the saved connections will be persisted.

**Comment by fialakarel** [comment]
@festlv :+1: Thank you for the tip. I extended the README.md as you suggested.
